### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by StevanWhite** [tom-anders/Easy_xkcd#191]
Love your app!

I don't care for excessive permissions, and I wonder if yours could be reduced.
Particularly, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE -- these are regarded "dangerous".

For a cache, one option is to use a database rather than writing files to disk explicitly.
For the "save" function, you could instead use more Android-esque "copy" and/or "share".

(I previously suggested using API calls to get a cache directory -- but my memory had slipped.  These require permissions as well.)

**Comment by markolo25** [comment]
hmm, this might collide with #228 which requests that we allow the user to copy a backup of their xckd comics from a backup/old phone instead of re-downloading the comics.

**Comment by SebiderSushi** [comment]
Due to your activity i revisited my own feature request #228 and realized that mine and this issue also heavily depend on how you're going to handle the rise of android 10 and especially 11 lately with their restrictions to shared storage access.

So in the long run, the READ/WRITE_EXTERNAL_STORAGE permissions are going to be replaced entirely with a MediaStore compatible  implementation that will use the Storage Access Framework below android 10, since [the minSdkLevel is 21](READ_EXTERNAL_STORAGE) anyway, right?

Any plans on that?

**Comment by tom-anders** [comment]
@StevanWhite @markolo25 @SebiderSushi So with the scoped storage being enforced when targeting Android 11, I have come up with the following plan:

1) Keep targeting Android 10 and set `requestLegacyExternalStorage` to `true` in the manifest
2) In the next update, move all files from the current location (usually `/storage/emulated/0/easy xkcd`) to the directory returned by [getExternalFilesDir()](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)l). At startup, I'll show an alert dialog explaining these changes.
3) After some time (say approx. 1 month) assume that all active users have successfully completed the migration. At that point, there will be another update that removes the READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions, removes the `requestLegacyExternalStorage` flag, and targets Android 11.
4) Users that have *not* completed the migration at this point will have to manually delete the old offline directory and the use the "Reload database" feature in the settings. The app should detect this and display an alert dialog at startup to inform the user.
5) Instead of allowing users to freely choose the offline directory, now only give the choice between internal and external storage, i.e. between `getExternalFilesDir()` and `getFilesDir()`

**Comment by tom-anders** [comment]
Steps 1) and 2) are included in version 7.3.10. To make sure everything goes smoothly, I only published this for 10% of users on Google Play and have not yet updated the F-Droid version yet. When there aren't any major issues, I'll publish to F-Droid and the rest of Google Play by tomorrow evening

**Comment by tom-anders** [comment]
The upcoming 8.0 release will remove `READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE` (and also `requestLegacyExternalStorage`). So I think this issue can be closed.
