### ISSUE TITLE
Consider moving/prompting on database rebuild

### ISSUE THREAD

**Issue by evelikov** [tom-anders/Easy_xkcd#263]
Semi-regularly I find myself using the "Reload Comic Database". Not sure why, the database needs fixing :shrug: 
Although nearly every time I end up looking for it under "Offline mode & notifications" - it is an offline feature after all.

Do you mind moving it and, optionally, adding a prompt when it's pressed? The process takes 4+ minutes due to my bad internet connection (Pixel 3 device fwiw) and I'd imagine handful of people have worse connection and/or slower devices.

Thanks in advance, hope the barrage of issue reports wasn't too much :bowing_man:

**Comment by tom-anders** [comment]
Actually, the database is also relevant if offline mode is disabled (it caches stuff like the title, alt text and URL). But adding a prompt sounds good, will do when I find some time.

**Comment by shlusiak** [comment]
Also a few ideas how to make this more user friendly:
- Download the JSONS highest to lowest, insert into database one by one, so the latest is in the database immediately
- Convert from ProgressDialog to an ongoing notification maybe
- As soon as the latest comic is downloaded, the app is usable and can show the ones that are downloaded by observing the database with `LiveData`.
- Ensure the HTTP client allows parallel requests. Not sure that is enabled by default, maybe that can be increased to download more than one and no doubt the latency is making this such a lengthy process, not the size of the data.
- I assume all the JSONs of all the comics never change, so to download them one by one seems very inefficient, as they could just be batched together into one JSON. Not sure Randall has an endpoint for that, but that could be done centralised rather than each device making 2000 requests.

**Comment by evelikov** [comment]
From a user POV `ProgressDialog to an ongoing notification maybe` would be amazing.

The rest sound like backend/developer specific - don't have a preference, but they sound perfectly reasonable.

**Comment by tom-anders** [comment]
The beta (and upcoming release 8.0) now download the comics dynamically, so I think this issue can be closed.
