### ISSUE TITLE
[Beta] Navbar color/contrast issues

### ISSUE THREAD

**Issue by WeirdAlex03** [tom-anders/Easy_xkcd#287]
App version: 8.0-beta1
OS version: Android 9
Device: Motorola moto g⁶

There are some color combinations that it very difficult (or literally impossible) to see tabs on the bottom navbar.

In light mode, setting the primary color to something dark makes it hard to see the non-selected tabs: ![Screenshot_20220315-113728.png](https://user-images.githubusercontent.com/33638869/158416871-814c5d19-6e65-4452-aaca-39ecf4d66fb9.png)

And black makes it literally impossible: ![Screenshot_20220315-113635.png](https://user-images.githubusercontent.com/33638869/158416165-582c6cdd-be69-46d1-adf0-7820b7cb97ae.png)

Likewise, setting the primary color to something bright makes the current tab hard to see: ![Screenshot_20220315-113751.png](https://user-images.githubusercontent.com/33638869/158417070-32f006f0-f8b8-4ae3-b938-ff3048f407ea.png)

Dark mode does not respect the primary color setting, and forces a color that makes the current tab hard to see: ![Screenshot_20220315-113916.png](https://user-images.githubusercontent.com/33638869/158417614-27390d02-2a9b-45a7-aefe-7790adc5e920.png)

**Comment by tom-anders** [comment]
I changed it to use the accent color when selected and just white otherwise (see below). Looks decent IMO

![backgroundnight](https://user-images.githubusercontent.com/13141438/162578506-a8c98c6b-75c9-4a11-a7d1-1ed8a0099fb4.png)
![color](https://user-images.githubusercontent.com/13141438/162578508-56f72c20-60de-4c7f-bb58-1fcea7343118.png)
